apiVersion: example.com/v1
kind: VisitorsApp
metadata:
  name: example-visitorsapp
spec:
  # Default values copied from <project_dir>/helm-charts/visitors-helm/values.yaml
  
  # Default values for visitors-helm.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.
  
  backend:
    size: 1
  
  frontend:
    title: Helm Operator Installed Visitors Site
  
