apiVersion: apps/v1
kind: Deployment
metadata:
  name: visitors-backend
spec:
  replicas: {{ .Values.backend.size }}
  selector:
    matchLabels:
      app: visitors
      tier: backend
  template:
    metadata:
      labels:
        app: visitors
        tier: backend
    spec:
      containers:
        - name: visitors-backend
          image: "jdob/visitors-service:latest"
          imagePullPolicy: Always
          ports:
            - name: visitors
              containerPort: 8000
          env:
            - name: MYSQL_DATABASE
              value: visitors
            - name: MYSQL_SERVICE_HOST
              value: mysql-service
